id: PE609F0FE
initial_creation_type: input
source_metadata:
  Title: Bauddha Stotra Saṃgraha
  Editor: Pandey, Janardan Shastri
  Publisher: Motilal Banarsidass
  Place of Publication: Varanasi
  Year: '1994'
  Śākyasiṃhastotram (brahmaṇā kṛtam):
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:28:36.225399'
last_modified_at: '2022-03-08T16:28:36.225407'
